blog/urls.py
# blog/urls.py

# django
from django.urls import path

# local
from . import views

app_name = "blog"

urlpatterns = [
	path("", views.BlogIndexView.as_view(), name="blog-index"),
]

mijnportfolio/urls.py
# mijnportflio/urls.py

# django
from django.urls import path

# local
from . import views

app_name = "mijnportfolio"

urlpatterns = [
	path("", views.PortfolioView.as_view(), name="portfolio"),
]

portfolio/urls.py
# portfolio/urls.py

# django
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
  path('admin/', admin.site.urls),
  # App urls
  path('', include('site_basis.urls', namespace="site-basis")),
  path('', include('mijnportfolio.urls', namespace="mijnportfolio")),
  path('', include('blog.urls', namespace="blog")),
  # debug urls
  #path("__debug__", include('debug_toolbar.urls')),
]

site_basis/urls.py
# site_basis/urls.py

# django
from django.urls import path

# local
from . import views

app_name = "site_basis"

urlpatterns = [
	path("", views.HomeView.as_view(), name="home"),
]

blog/models.py
# blog/models.py

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


# Blog model
class Blog(models.Model):
  class Meta:
    verbose_name        = 'Blog'
    verbose_name_plural = 'Blog Profiles'
    ordering            = ["timestamp"]

  name        = models.CharField(max_length=200, blank=True, null=True)
  description = models.CharField(max_length=500, blank=True, null=True)
  body        = RichTextField(blank=True, null=True)
  image       = models.ImageField(blank=True, null=True, upload_to="blog")
  author      = models.CharField(max_length=200, blank=True, null=True)
  timestamp   = models.DateTimeField(auto_now_add=True)
  slug        = models.SlugField(null=True, blank=True)
  is_active   = models.BooleanField(default=True)

  def save(self, *args, **kwargs):
    if not self.id:
      self.slug = slugify(self.name)
    super(Blog, self).save(*args, **kwargs)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return f"/blog/{self.slug}"

mijnportfolio/models.py
# mijnportfolio/models.py

# django
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# packages
from ckeditor.fields import RichTextField


# Skill model
class Skill(models.Model):
  class Meta:
    verbose_name        = 'Skill'
    verbose_name_plural = 'Skills'
  # attributes
  name         = models.CharField(max_length=20, blank=True, null=True)
  score        = models.IntegerField(default=80, blank=True, null=True)
  image        = models.FileField(blank=True, null=True, upload_to="skills")
  is_key_skill = models.BooleanField(default=False)
    
  def __str__(self):
    return self.name

# Userprofile model
class UserProfile(models.Model):
  class Meta:
    verbose_name        = 'User Profile'
    verbose_name_plural = 'User Profiles'
  # attributes
  avatar = models.ImageField(blank=True, null=True, upload_to="avatar")
  title  = models.CharField(max_length=200, blank=True, null=True)
  bio    = models.TextField(blank=True, null=True)
  cv     = models.FileField(blank=True, null=True, upload_to="cv")
  # relaties
  user   = models.OneToOneField(User, on_delete=models.CASCADE)
  skills = models.ManyToManyField(Skill, blank=True)

  def __str__(self):
    return f'{self.user.first_name} {self.user.last_name}'

# ContactProfile model
class ContactProfile(models.Model):
  class Meta:
    verbose_name        = 'Contact Profile'
    verbose_name_plural = 'Contact Profiles'
    ordering            = ["timestamp"]
  # attributes
  name      = models.CharField(verbose_name="Name",max_length=100)
  email     = models.EmailField(verbose_name="Email")
  message   = models.TextField(verbose_name="Message")
  # secundair
  timestamp = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return f'{self.name}'

# Testimonial model
class Testimonial(models.Model):
  class Meta:
    verbose_name        = 'Testimonial'
    verbose_name_plural = 'Testimonials'
    ordering            = ["name"]
  # attributes
  name      = models.CharField(max_length=200, blank=True, null=True)
  role      = models.CharField(max_length=200, blank=True, null=True)
  thumbnail = models.ImageField(blank=True, null=True, upload_to="testimonials")
  quote     = models.CharField(max_length=500, blank=True, null=True)
  is_active = models.BooleanField(default=True)

  def __str__(self):
    return self.name

# Media model
class Media(models.Model):
  class Meta:
    verbose_name        = 'Media'
    verbose_name_plural = 'Media Files'
    ordering            = ["name"]
	# attributes
  name     = models.CharField(max_length=200, blank=True, null=True)
  url      = models.URLField(blank=True, null=True)
  image    = models.ImageField(blank=True, null=True, upload_to="media")
  is_image = models.BooleanField(default=True)

  def save(self, *args, **kwargs):
    if self.url:
      self.is_image = False
    super(Media, self).save(*args, **kwargs)
  def __str__(self):
    return self.name

# Portfolio model
class Portfolio(models.Model):
  class Meta:
    verbose_name        = 'Portfolio'
    verbose_name_plural = 'Portfolio Profiles'
    ordering            = ["name"]
  # attributes
  name        = models.CharField(max_length=200, blank=True, null=True)
  description = models.CharField(max_length=500, blank=True, null=True)
  body        = RichTextField(blank=True, null=True)
  image       = models.ImageField(blank=True, null=True, upload_to="portfolio")
  date        = models.DateTimeField(blank=True, null=True)
  slug        = models.SlugField(null=True, blank=True)
  is_active   = models.BooleanField(default=True)

  def save(self, *args, **kwargs):
    if not self.id:
      self.slug = slugify(self.name)
    super(Portfolio, self).save(*args, **kwargs)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return f"/portfolio/{self.slug}"

# Certificate model
class Certificate(models.Model):
  class Meta:
    verbose_name        = 'Certificate'
    verbose_name_plural = 'Certificates'
  # attributes
  name        = models.CharField(max_length=50, blank=True, null=True)
  description = models.CharField(max_length=500, blank=True, null=True)
  title       = models.CharField(max_length=200, blank=True, null=True)
  date        = models.DateTimeField(blank=True, null=True)
  is_active   = models.BooleanField(default=True)

  def __str__(self):
    return self.name

site_basis/models.py
from django.db import models

# Create your models here.

blog/views.py
# blog/views.py

from django.shortcuts import render
from django.views import generic

# home view
# classbased view 
class BlogIndexView(generic.TemplateView):
	"""
    Website home page.

    **Template:**

    :template:`blog/blog.html`
    """
	template_name = "blog/blog.html"

mijnportfolio/views.py
# mijnportfolio/views.py

from django.shortcuts import render
from django.views import generic

# portfolio view
# classbased view 
class PortfolioView(generic.TemplateView):
	"""
    Website portfolio page.

    **Template:**

    :template:`mijnportfolio/portfolio.html`
    """
	template_name = "mijnportfolio/portfolio.html"

site_basis/views.py
# site_basis/views.py

from django.shortcuts import render
from django.views import generic

# home view
# classbased view 
class HomeView(generic.TemplateView):
	"""
    Website home page.

    **Template:**

    :template:`site_basis/home.html`
    """
	template_name = "site_basis/home.html"

blog/templates/blog/blog.html
<!-- portfolio/templates/portfolio/blog.html -->

{% extends 'portfolio/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}All blogs{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">See my recent blogs below</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
            <div class="col-md-6 pColMain">
              <div class="pCol">
                <a href="{% url 'portfolio:blog-detail' slug=obj.slug %}" >
                <img src="{{obj.image.url}}" alt="..." class="pImg">
                </a>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%} 
    

blog/templates/blog/blog_detail.html
<!-- portfolio/templates/portfolio/blog_detail.html -->

{% extends 'portfolio/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}Blog detail{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">{{object.name|title}}</h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-auto">
          <div class="authorCol">
            <h4 class="smTitle pb-3">{{object.author|title}}</h4>
          </div>
        </div>
        <div class="col-md">
          <h4 class="smTitle pb-3">{{object.timestamp.date}}</h4>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm">
    <div class="container">
      {{object.body|safe}}
    </div>
  </div>
</section>

{% endblock %}
<!-- ================================
End Content
================================= -->
   

mijnportfolio/templates/mijnportfolio/home_portfolio.html
<!-- portfolio/templates/portfolio/index.html -->

{% extends 'base.html' %}
{% load static %}

{% block title %} {{ title }} {% endblock title %}


{% block css_files %}
  <link rel="stylesheet" href="{% static 'portfolio/styles/main.css' %}">
{% endblock css_files%}

{% block content %}
  <div class="container">
    <h2>home portfolio</h2>
    <br><br>
    <div class="row">
      <div class="col-md-3">
        <div id="profile-wrapper" class="card card-body border-info h-100">
          <img id="profile-pic" src="{% static 'portfolio/images/standard.jpg' %}">
          <hr>
          <h4>Casper</h4>
          <p>Coding architect</p>
        </div>
      </div>
      <div class="col-md-9">
        <div class="card card-body border-info h-100">
          <h4>Mijn werkzaamheden</h4>
          <hr>
          <p>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce ullamcorper dapibus nisl. In id dui. Nunc pulvinar erat et nibh.
             Integer sollicitudin. Quisque faucibus. Sed eleifend sapien sed nunc. Pellentesque congue leo et felis eleifend scelerisque. 
             In a mauris ultricies diam tincidunt pharetra. Etiam venenatis facilisis orci. Donec quam dui, mattis eu, posuere a, tristique ut,
              pede. Sed quis nibh. Praesent augue metus, dapibus ac, consectetuer a, convallis eu, elit. Etiam et dui.
          </p>
          <p>
            Cras tempus, tellus quis facilisis dignissim, lorem libero rhoncus dolor, in venenatis neque arcu a mauris. Vivamus arcu quam,
             egestas sed, tempor quis, imperdiet sit amet, justo. Aliquam sem ipsum, sagittis id, imperdiet eu, scelerisque non, lorem. 
             Cras aliquet, augue gravida iaculis tincidunt, elit sapien egestas libero, in dictum ipsum velit vel orci. Etiam mi nulla, 
             lacinia nec, pretium vitae, blandit vel, tortor. Praesent eget libero. In accumsan laoreet lacus. Vivamus enim.
          </p>
          <ul class="social-links">
            <li>
              <a href="https://facebook.com" target="_blank" rel="noopener"><i class="fab fa-facebook social"></i></a>
            </li>
            <li>
              <a href="https://twitter.com" target="_blank" rel="noopener"><i class="fab fa-twitter social"></i></a>
            </li>
            <li>
              <a href="https://linkedin.com" target="_blank" rel="noopener"><i class="fab fa-linkedin social"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-6">
        <div class="card card-body">
          <h4>Mijn Ervaring</h4>
          <hr>
          <p>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce ullamcorper dapibus nisl. In id dui. Nunc pulvinar erat et nibh.
             Integer sollicitudin. Quisque faucibus. Sed eleifend sapien sed nunc. Pellentesque congue leo et felis eleifend scelerisque. 
             In a mauris ultricies diam tincidunt pharetra. Etiam venenatis facilisis orci. Donec quam dui, mattis eu, posuere a, tristique ut,
              pede. Sed quis nibh. Praesent augue metus, dapibus ac, consectetuer a, convallis eu, elit. Etiam et dui.
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card card-body">
          <h4>Mijn Expertise</h4>
          <hr>
          <p>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce ullamcorper dapibus nisl. In id dui. Nunc pulvinar erat et nibh.
             Integer sollicitudin. Quisque faucibus. Sed eleifend sapien sed nunc. Pellentesque congue leo et felis eleifend scelerisque. 
             In a mauris ultricies diam tincidunt pharetra. Etiam venenatis facilisis orci. Donec quam dui, mattis eu, posuere a, tristique ut,
              pede. Sed quis nibh. Praesent augue metus, dapibus ac, consectetuer a, convallis eu, elit. Etiam et dui.
          </p>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-6">
        <div class="card card-body">
          <h4>Mijn manier van werken</h4>
          <hr>
          <p>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce ullamcorper dapibus nisl. In id dui. Nunc pulvinar erat et nibh.
             Integer sollicitudin. Quisque faucibus. Sed eleifend sapien sed nunc. Pellentesque congue leo et felis eleifend scelerisque. 
             In a mauris ultricies diam tincidunt pharetra. Etiam venenatis facilisis orci. Donec quam dui, mattis eu, posuere a, tristique ut,
              pede. Sed quis nibh. Praesent augue metus, dapibus ac, consectetuer a, convallis eu, elit. Etiam et dui.
          </p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card card-body">
          <h4>Mijn doelen</h4>
          <hr>
          <p>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Fusce ullamcorper dapibus nisl. In id dui. Nunc pulvinar erat et nibh.
             Integer sollicitudin. Quisque faucibus. Sed eleifend sapien sed nunc. Pellentesque congue leo et felis eleifend scelerisque. 
             In a mauris ultricies diam tincidunt pharetra. Etiam venenatis facilisis orci. Donec quam dui, mattis eu, posuere a, tristique ut,
              pede. Sed quis nibh. Praesent augue metus, dapibus ac, consectetuer a, convallis eu, elit. Etiam et dui.
          </p>
        </div>
      </div>
    </div>
  </div>
  <br>
{% endblock content %}

mijnportfolio/templates/mijnportfolio/index_portfolio.html
<!-- portfolio/templates/portfolio/index_portfolio.html -->

{% extends 'portfolio/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}Resume{% endblock %}
{% block decription %}Resume website{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="bannerSection">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-auto order-md-last">
          <div class="bannerUserImg">
            <img src="{{me.userprofile.avatar.url}}" alt="{{me.first_name|title}} {{me.last_name|title}} avatar">
          </div>
        </div>
        <div class="col-md">
          <div class="bannerContent">
            <h1 class="xlTitle pb-3">Hi, I’m {{me.first_name|title}}, <br> a {{me.userprofile.title}} </br></h1>
            <p>{{me.userprofile.bio}}</p>
            <div class="bannerBtnCol">
              <div class="row">
                <div class="col-auto">
                  <a download href="{{me.userprofile.cv.url}}" class="btn btnPrimary">Download Resume</a>
                </div>
                <div class="col-auto">
                  <a href="{% url 'portfolio:contact' %}" class="btn btnOutline">Contact</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpace pt-0">
    <div class="container">
      <div class="row">
        <div class="col-md-auto">
          <div class="keySkillCol">
            <h4 class="smTitle pb-3">Key Skills</h4>
            {% for sk in me.userprofile.skills.all %}
            {% if sk.is_key_skill %}
            <div class="keySkillCard">
              {% if sk.image %}
              <div class="ksIconCol">
                <img src="{{sk.image.url}}" alt="...">
              </div>
              {% endif %}
              <span class="ksText">{{sk.name}}</span>
            </div>
            {% endif %}
            {% endfor %}
          </div>
        </div>
        <div class="col-md">
          <h4 class="smTitle pb-3">Coding Skills</h4>
          <div class="progressCol">
            <div class="progressCard">
              {% for sk in me.userprofile.skills.all %}
                {% if not sk.is_key_skill %}
                <div class="progressCol">
                  <span class="progressLbl">{{sk.name}}</span>
                  <div class="row g-2 align-items-center">
                    <div class="col">
                      <div class="progress progressStyle">
                        <div class="progress-bar" role="progressbar" style="width: {{sk.score}}%" aria-valuenow="{{sk.score}}" aria-valuemin="0" aria-valuemax="100"></div>
                      </div>
                    </div>
                    <div class="col-auto">
                      <span class="pLbl">{{sk.score}}%</span>
                    </div>
                  </div>
                </div>
                {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Certificates</h4>
        </div>
      </div>
      <div class="sliderOuter">
        <div class="swiper certificatesSlider">
          <div class="swiper-wrapper">
            {% for c in certificates %}
              {% if c.is_active %}
              <div class="swiper-slide">
                <div class="cardStyle1">
                  <h4 class="mdTitle cs1Title">
                    <a href="javascript:void(0)">{{c.title}}</a>
                  </h4>
                  <ul class="cardOptionCol">
                    <li>{{c.date.date}}</li>
                    <li>{{c.name|title}}</li>
                  </ul>
                  <p>{{c.description}}</p>
                </div>
              </div>
              {% endif %}
            {% endfor %}
          </div>
        </div>            
        <div class="cert-swiper-button-next swiper-button-next swiperBtnStyle"></div>
        <div class="cert-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
        <div class="swiper-pagination swiperPaginationStyle posInitial"></div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpace">
    <div class="container">
      <div class="portfolioCol">
        <div class="row pb-3">
          <div class="col">
            <h4 class="smText regular">Featured Work</h4>
          </div>
          <div class="col-auto">
            <a href="{% url 'portfolio:portfolios' %}" class="simpleLink">View all</a>
          </div>
        </div>
        {% for p in portfolio %}
          {% if p.is_active %}
          <div class="portfolioCard">
            <div class="row g-4 align-items-center">
              <div class="col-md-auto">
                <div class="portfolioImgCol">
                  <a href="{% url 'portfolio:portfolio-detail' slug=p.slug %}"><img src="{{p.image.url}}" alt="..."></a>
                </div>
              </div>
              <div class="col-md">
                <div class="portfolioContentCol">
                  <h4 class="lgTitle"><a href="{% url 'portfolio:portfolio-detail' slug=p.slug %}">{{p.name}}</a></h4>
                  <ul class="portfolioOption">
                    <li><span class="dateLbl">{{p.date.year}}</span></li>
                  </ul>
                  <p>{{p.description}}</p>
                </div>
              </div>
            </div>
          </div>
          {% endif %}
        {% endfor %}
      </div>
      <div class="testimonialCol">
        <h4 class="smText regular d-block">Testimonials</h4>
        <div class="testimonialSlider">
          <div class="swiper testimonialSwiper">
            <div class="swiper-wrapper">
              {% for t in testimonials %}
                {% if t.is_active %}
                <div class="swiper-slide">
                  <div class="testimonialCard">
                    <div class="row align-items-center">
                      <div class="col-sm-auto">
                        <div class="tImgCol">
                          <img src="{{t.thumbnail.url}}" alt="...">
                        </div>
                      </div>
                      <div class="col-sm">
                        <div class="tContentCol">
                          <h4 class="xsTitle bold">{{t.name}} - {{t.role}}</h4>
                          <p>{{t.quote}}</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {% endif %}
              {% endfor %}
            </div>
            <div class="test-swiper-button-next swiper-button-next swiperBtnStyle"></div>
            <div class="test-swiper-button-prev swiper-button-prev swiperBtnStyle"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Recent posts</h4>
        </div>
        <div class="col-auto">
          <a href="{% url 'portfolio:blogs' %}" class="simpleLink">View all</a>
        </div>
      </div>
      <div class="row g-3">
      {% for b in blogs %}
        {% if b.is_active %}
          <div class="col-lg-6">
            <div class="cardStyle1">
              <h4 class="mdTitle cs1Title"><a href="{% url 'portfolio:blog-detail' slug=b.slug %}">{{b.name}}</a></h4>
              <ul class="cardOptionCol">
                <li>{{b.timestamp.date}}</li>
                <li>{{b.author}}</li>
              </ul>
              <p>{{b.description}}</p>
            </div>
          </div>
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</section>
{% endblock %}
<!-- ================================
End Content
================================= -->

mijnportfolio/templates/mijnportfolio/portfolio.html
<!-- portfolio/templates/portfolio/portfolio.html -->

{% extends 'portfolio/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}All portfolio{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">See my recent projects below</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
            <div class="col-md-6 pColMain">
              <div class="pCol">
                <a href="{% url 'portfolio:portfolio-detail' slug=obj.slug %}" >
                <img src="{{obj.image.url}}" alt="..." class="pImg">
                </a>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{% endblock%}    

site_basis/templates/site_basis/home.html
<!-- site_basis/templates/site_basis/home.html -->

{% extends 'site_basis/base.html' %}

{% block content %}
  <h1>Welkom bij mijn portfolio site</h1>
{% endblock content %}

site_basis/templates/site_basis/includes/breadcrumb.html
<!-- templates/includes/breadcrumb.html -->

<div class="container">
  <div class="row">
    <div class="col-12">
      <a href="{% url 'site-basis:home' %}"><i class="fa fa-home"></i> Home</a> / {{ title }}
    </div>
    <hr/>
  </div>
  <h2>{{ title }}</h2>
</div>

site_basis/templates/site_basis/includes/footer.html
<!-- templates/includes/footer.html -->

{% load static %}

<footer class="footer-area">
  <div class="container">
    <!-- Copywrite Area -->
    <div class="row">
      <div class="col-12">
        <div class="copywrite-content">
          <p>Copyright &copy;  All rights reserved</p>
        </div>
      </div>
    </div>
  </div>
</footer>

site_basis/templates/site_basis/includes/navbar.html
<!-- templates/includes/navbar.html -->

{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- Logo -->
  <a class="nav-brand" href="{% url 'site-basis:home' %}"><img src="{% static 'images/logo.png' %}" alt=""></a>
<!-- buttons -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <!-- Linkerkant van de Navbar -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><a class="nav-link" href="{% url 'site-basis:home' %}">Home </a></li>
    </ul>
  </div>
</nav>

site_basis/templates/site_basis/partials/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
    {% endfor %}
{% endif %}